services:
  api:
    build: ./
    command: yarn start
    stdin_open: true
    volumes:
      - ./src:/app/src
    ports:
      - ${PORT}:8000
    environment:
      - NODE_ENV=development
      - DB_URL=postgres://postgres:postgres@postgres/wildermine

  postgres:
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5438:5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql

  