services:
  front:
    build:
      context: ../front
      dockerfile: ./Dockerfile-prod
    command: serve -s build
    ports:
      - 3000:3000
    volumes:
      - ../front/src:/app/src
    depends_on:
      - api
  api:
    env_file:
    - ./.env
    - ./env-prod.env
    build:
      context: .
      dockerfile: ./Dockerfile-prod
    command: yarn start
    stdin_open: true
    volumes:
      - ./src:/app/src
    ports:
      - ${PORT}:8000
    depends_on:
      - postgres

  postgres:
    env_file:
      - .env
      - .env-prod.env
    image: postgres:14.1
    restart: always
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql

  