FROM node:lts-alpine as builder

WORKDIR /app

COPY tsconfig.json ./
COPY package*.json ./
COPY .env ./
COPY env-prod.env ./


RUN yarn
RUN yarn global add typescript

COPY src ./src

RUN yarn build

FROM node:lts-alpine

WORKDIR /app

COPY --from=builder /app/dist /app/dist

RUN apk --no-cache add curl

COPY package*.json ./
COPY .env ./
COPY ./env-prod.env ./

RUN yarn install --production

CMD yarn start

