version: '3'

services:
  server:
    image: getshitdonewild/getshitdone-back 
    command: sh -c "yarn build && yarn seed:staging &&yarn start"
    env_file:
    - ./.env
    - ./env-prod.env
    expose:
      - 5000
    # environment:
    #   - NODE_ENV=production
    #   - SERVER_PORT=5000
    depends_on:
      - postgres
  client:
    image: getshitdonewild/getshitdone-front
    command: sh -c "yarn build"
    volumes:
      - web-client-build:/app/build
    environment:
      - NODE_ENV=production  
  postgres:
    env_file:
      - .env
      - env-prod.env
    image: postgres:14.1
    restart: always
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/:/docker-entrypoint-initdb.d/
  nginx:
    image: nginx:1.21.3
    depends_on:
      - server
      - client
    restart: always
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build
      - ./logs:/var/log/nginx
volumes:
  web-client-build:
