services:
  front:
    build:
      context: ../front
      dockerfile: ./Dockerfile-dev
    command: yarn start
    ports:
      - 3000:3000
    volumes:
      - ../front/src:/app/src
    depends_on:
      - api
  api:
    build: 
      context: .
      dockerfile: ./Dockerfile-dev
    command: yarn start:dev
    stdin_open: true
    volumes:
      - ./src:/app/src
    env_file:
      - ./.env
      - ./env-dev.env
    ports:
      - ${PORT}:8000

    depends_on:
      - postgres

  postgres:
    env_file:
      - ./.env
      - ./env-dev.env
    image: postgres:14.1
    restart: always
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql

  