name: dockerhub-ci-staging

on:
  push:
    branches:
      - 'staging'

jobs:
  stagingToMain:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - uses: actions/checkout@v3
      - name: Create Pull Request to Main
        uses: peter-evans/create-pull-request@v3.10.1
        with:
          commit-message: Auto Pull Request
          title: Automated PR branch staging to Prod
          body: After you valid the changes in staging environnement, just press the button, the production are to be released
          branch: ${{ github.ref }} # The branch where you commit
          base: main # Don't forget to specify the right base branch here
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check out code
        uses: actions/checkout@v2
      - name: Create env file
        run: |
          touch .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.PASSWORD }} >> .env
          echo DB_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/wildermine >> .env
          cat .env
      - name: Create env prod file
        run: |
          touch env-prod.env
          echo TYPEORM_ENTITIES=dist/entity/*.js >> env-prod.env
          cat env-prod.env
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile-staging
          push: true
          tags: getshitdonewild/getshitdone-back-staging:latest
