name: dockerhub-ci-staging

on:
  push:
    branches:
      - 'staging'

jobs:
  stagingToMain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Create PR to PROD
        uses: peter-evans/create-pull-request@v4
        with:
          branch: main-staging
  # docker:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1
  #     - name: Login to DockerHub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     - name: Check out code
  #       uses: actions/checkout@v2
  #     - name: Create env file
  #       run: |
  #         touch .env
  #         echo PORT=${{ secrets.PORT }} >> .env
  #         echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
  #         echo POSTGRES_PASSWORD=${{ secrets.PASSWORD }} >> .env
  #         echo DB_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/wildermine >> .env
  #         cat .env
  #     - name: Create env prod file
  #       run: |
  #         touch env-prod.env
  #         echo TYPEORM_ENTITIES=dist/entity/*.js >> env-prod.env
  #         cat env-prod.env
  #     - name: Build and push
  #       id: docker_build
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: ./
  #         file: ./Dockerfile-staging
  #         push: true
  #         tags: getshitdonewild/getshitdone-back-staging:latest
